const DataManifest = [
{ src: "./data/fnt/PressStart2P.fnt", name: "PressStart2P", type: "binary" },
{ src: "./data/fnt/PressStart2P.png", name: "PressStart2P", type: "image" },
{ src: "./data/img/107.png", name: "107", type: "image" },
{ src: "./data/img/108.png", name: "108", type: "image" },
{ src: "./data/img/115.png", name: "115", type: "image" },
{ src: "./data/img/122.png", name: "122", type: "image" },
{ src: "./data/img/123.png", name: "123", type: "image" },
{ src: "./data/img/124.png", name: "124", type: "image" },
{ src: "./data/img/125_part.png", name: "125_part", type: "image" },
{ src: "./data/img/125.png", name: "125", type: "image" },
{ src: "./data/img/127.png", name: "127", type: "image" },
{ src: "./data/img/134.png", name: "134", type: "image" },
{ src: "./data/img/135.png", name: "135", type: "image" },
{ src: "./data/img/136.png", name: "136", type: "image" },
{ src: "./data/img/137.png", name: "137", type: "image" },
{ src: "./data/img/138.png", name: "138", type: "image" },
{ src: "./data/img/140.png", name: "140", type: "image" },
{ src: "./data/img/141.png", name: "141", type: "image" },
{ src: "./data/img/142.png", name: "142", type: "image" },
{ src: "./data/img/36.png", name: "36", type: "image" },
{ src: "./data/img/41.png", name: "41", type: "image" },
{ src: "./data/img/61.png", name: "61", type: "image" },
{ src: "./data/img/83cc92e895a4fcfb.png", name: "83cc92e895a4fcfb", type: "image" },
{ src: "./data/img/briefumschlag-kl.png", name: "briefumschlag-kl", type: "image" },
{ src: "./data/img/by_foorbie.png", name: "by_foorbie", type: "image" },
{ src: "./data/img/by_p5t.png", name: "by_p5t", type: "image" },
{ src: "./data/img/c90963e341da1cec.png", name: "c90963e341da1cec", type: "image" },
{ src: "./data/img/chill_zone.png", name: "chill_zone", type: "image" },
{ src: "./data/img/cija_32x32_basic_CC0.png", name: "cija_32x32_basic_CC0", type: "image" },
{ src: "./data/img/follow_me.png", name: "follow_me", type: "image" },
{ src: "./data/img/guest_art.png", name: "guest_art", type: "image" },
{ src: "./data/img/kawaiipunk - AntiFa Area No Copsz.png", name: "kawaiipunk - AntiFa Area No Copsz", type: "image" },
{ src: "./data/img/kawaiipunk - brutualistpunk.png", name: "kawaiipunk - brutualistpunk", type: "image" },
{ src: "./data/img/kawaiipunk - London.png", name: "kawaiipunk - London", type: "image" },
{ src: "./data/img/kawaiipunk - self portrait.png", name: "kawaiipunk - self portrait", type: "image" },
{ src: "./data/img/kittenmews.png", name: "kittenmews", type: "image" },
{ src: "./data/img/minideko.png", name: "minideko", type: "image" },
{ src: "./data/img/on_mastodon.png", name: "on_mastodon", type: "image" },
{ src: "./data/img/orchidee.png", name: "orchidee", type: "image" },
{ src: "./data/img/pull_requests_welcome.png", name: "pull_requests_welcome", type: "image" },
{ src: "./data/img/rc3-2021-mullana-utility.png", name: "rc3-2021-mullana-utility", type: "image" },
{ src: "./data/img/rc3-mullana-floor-wall.png", name: "rc3-mullana-floor-wall", type: "image" },
{ src: "./data/img/riss-kl.png", name: "riss-kl", type: "image" },
{ src: "./data/img/star_s.png", name: "star_s", type: "image" },
{ src: "./data/img/talk_cafe.png", name: "talk_cafe", type: "image" },
{ src: "./data/img/texts.png", name: "texts", type: "image" },
{ src: "./data/img/want_to_share_your_art.png", name: "want_to_share_your_art", type: "image" },
{ src: "./data/img/work_in_progress.png", name: "work_in_progress", type: "image" },
{ src: "./data/map/artworld.tmx", name: "artworld", type: "tmx" },
]; export default DataManifest;
