const DataManifest = [
{ src: "./data/artworks/kittenmews/km_107.png",  name: "km_107", type: "image" },
{ src: "./data/artworks/kittenmews/km_108.png",  name: "km_108", type: "image" },
{ src: "./data/artworks/kittenmews/km_115.png",  name: "km_115", type: "image" },
{ src: "./data/artworks/kittenmews/km_122.png",  name: "km_122", type: "image" },
{ src: "./data/artworks/kittenmews/km_123.png",  name: "km_123", type: "image" },
{ src: "./data/artworks/kittenmews/km_124.png",  name: "km_124", type: "image" },
{ src: "./data/artworks/kittenmews/km_125_part.png",  name: "km_125_part", type: "image" },
{ src: "./data/artworks/kittenmews/km_125.png",  name: "km_125", type: "image" },
{ src: "./data/artworks/kittenmews/km_127.png",  name: "km_127", type: "image" },
{ src: "./data/artworks/kittenmews/km_134.png",  name: "km_134", type: "image" },
{ src: "./data/artworks/kittenmews/km_135.png",  name: "km_135", type: "image" },
{ src: "./data/artworks/kittenmews/km_136.png",  name: "km_136", type: "image" },
{ src: "./data/artworks/kittenmews/km_137.png",  name: "km_137", type: "image" },
{ src: "./data/artworks/kittenmews/km_138.png",  name: "km_138", type: "image" },
{ src: "./data/artworks/kittenmews/km_140.png",  name: "km_140", type: "image" },
{ src: "./data/artworks/kittenmews/km_141.png",  name: "km_141", type: "image" },
{ src: "./data/artworks/kittenmews/km_142.png",  name: "km_142", type: "image" },
{ src: "./data/artworks/kittenmews/km_36.png",  name: "km_36", type: "image" },
{ src: "./data/artworks/kittenmews/km_41.png",  name: "km_41", type: "image" },
{ src: "./data/artworks/kittenmews/km_61.png",  name: "km_61", type: "image" },
{ src: "./data/artworks/kittenmews/km_132.png",  name: "km_132", type: "image" },
{ src: "./data/artworks/kittenmews/km_133.png",  name: "km_133", type: "image" },
{ src: "./data/artworks/kittenmews/km_79.png",  name: "km_79", type: "image" },
{ src: "./data/artworks/p5t/p5t_star.png",  name: "p5t_star", type: "image" },
{ src: "./data/artworks/foorbie/foorbie_orchidee.png",  name: "foorbie_orchidee", type: "image" },
{ src: "./data/artworks/foorbie/foorbie_briefumschlag.png",  name: "foorbie_briefumschlag", type: "image" },
{ src: "./data/artworks/foorbie/foorbie_riss.png",  name: "foorbie_riss", type: "image" },
{ src: "./data/artworks/lyrilith/lyrilith_83cc92e895a4fcfb.png",  name: "lyrilith_83cc92e895a4fcfb", type: "image" },
{ src: "./data/artworks/lyrilith/lyrilith_c90963e341da1cec.png",  name: "lyrilith_c90963e341da1cec", type: "image" },
{ src: "./data/artworks/kawaiipunk/kawaiipunk_AntiFa_Area_No_Copsz.png",  name: "kawaiipunk_AntiFa_Area_No_Copsz", type: "image" },
{ src: "./data/artworks/kawaiipunk/kawaiipunk_brutualistpunk.png",  name: "kawaiipunk_brutualistpunk", type: "image" },
{ src: "./data/artworks/kawaiipunk/kawaiipunk_london.png",  name: "kawaiipunk_london", type: "image" },
{ src: "./data/artworks/kawaiipunk/kawaiipunk_self_portrait.png",  name: "kawaiipunk_self_portrait", type: "image" },
{ src: "./data/characters/sample_character_01.png",  name: "sample_character_01", type: "image" },
{ src: "./data/characters/sample_character_02.png",  name: "sample_character_02", type: "image" },
{ src: "./data/characters/sample_character_03.png",  name: "sample_character_03", type: "image" },
{ src: "./data/characters/sample_character_04.png",  name: "sample_character_04", type: "image" },
{ src: "./data/characters/sample_character_05.png",  name: "sample_character_05", type: "image" },
{ src: "./data/characters/sample_character_06.png",  name: "sample_character_06", type: "image" },
{ src: "./data/characters/sample_character_07.png",  name: "sample_character_07", type: "image" },
{ src: "./data/characters/sample_character_08.png",  name: "sample_character_08", type: "image" },
{ src: "./data/characters/sample_character_09.png",  name: "sample_character_09", type: "image" },
{ src: "./data/characters/sample_character_10.png",  name: "sample_character_10", type: "image" },
{ src: "./data/characters/sample_character_11.png",  name: "sample_character_11", type: "image" },
{ src: "./data/characters/sample_character_12.png",  name: "sample_character_12", type: "image" },
{ src: "./data/characters/sample_character_13.png",  name: "sample_character_13", type: "image" },
{ src: "./data/characters/sample_character_14.png",  name: "sample_character_14", type: "image" },
{ src: "./data/characters/sample_character_15.png",  name: "sample_character_15", type: "image" },
{ src: "./data/characters/sample_character_16.png",  name: "sample_character_16", type: "image" },
{ src: "./data/fnt/PressStart2P.fnt",  name: "PressStart2P", type: "binary" },
{ src: "./data/fnt/PressStart2P.png",  name: "PressStart2P", type: "image" },
{ src: "./data/map/lobby.tmx",  name: "lobby", type: "tmx" },
{ src: "./data/map/artworld.tmx",  name: "artworld", type: "tmx" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Cat 01-1.png",  name: "Cat 01-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Cat 01-1r.png",  name: "Cat 01-1r", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Cat 01-2.png",  name: "Cat 01-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Cat 01-3.png",  name: "Cat 01-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Cat-01-2r.png",  name: "Cat-01-2r", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Cat-01-3r.png",  name: "Cat-01-3r", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Dog 01-1.png",  name: "Dog 01-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Dog 01-1r.png",  name: "Dog 01-1r", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Dog 01-2.png",  name: "Dog 01-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Dog 01-3.png",  name: "Dog 01-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Dog-01-2r.png",  name: "Dog-01-2r", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Animal/Dog-01-3r.png",  name: "Dog-01-3r", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Boss/Boss 01.png",  name: "Boss 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 01-1.png",  name: "Enemy 01-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 02-1.png",  name: "Enemy 02-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 03-1.png",  name: "Enemy 03-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 04-1.png",  name: "Enemy 04-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 05-1.png",  name: "Enemy 05-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 06-1.png",  name: "Enemy 06-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 07-1.png",  name: "Enemy 07-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 08-1.png",  name: "Enemy 08-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 09-1.png",  name: "Enemy 09-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 10-1.png",  name: "Enemy 10-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 11-1.png",  name: "Enemy 11-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 12-1.png",  name: "Enemy 12-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 13-1.png",  name: "Enemy 13-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 14-1.png",  name: "Enemy 14-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 15-1.png",  name: "Enemy 15-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 15-2.png",  name: "Enemy 15-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 15-3.png",  name: "Enemy 15-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 15-4.png",  name: "Enemy 15-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 15-5.png",  name: "Enemy 15-5", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 15-6.png",  name: "Enemy 15-6", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-1.png",  name: "Enemy 16-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-2.png",  name: "Enemy 16-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-3.png",  name: "Enemy 16-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-4.png",  name: "Enemy 16-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-5.png",  name: "Enemy 16-5", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-6.png",  name: "Enemy 16-6", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-7.png",  name: "Enemy 16-7", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 16-8.png",  name: "Enemy 16-8", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-1.png",  name: "Enemy 17-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-2.png",  name: "Enemy 17-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-3.png",  name: "Enemy 17-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-4.png",  name: "Enemy 17-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-5.png",  name: "Enemy 17-5", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-6.png",  name: "Enemy 17-6", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-7.png",  name: "Enemy 17-7", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 17-8.png",  name: "Enemy 17-8", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 18.png",  name: "Enemy 18", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 19.png",  name: "Enemy 19", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 20.png",  name: "Enemy 20", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 21.png",  name: "Enemy 21", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Enemy/Enemy 22.png",  name: "Enemy 22", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 01-1.png",  name: "Female 01-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 01-2.png",  name: "Female 01-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 01-3.png",  name: "Female 01-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 01-4.png",  name: "Female 01-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 02-1.png",  name: "Female 02-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 02-2.png",  name: "Female 02-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 02-3.png",  name: "Female 02-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 02-4.png",  name: "Female 02-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 03-1.png",  name: "Female 03-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 03-2.png",  name: "Female 03-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 03-3.png",  name: "Female 03-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 03-4.png",  name: "Female 03-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 04-1.png",  name: "Female 04-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 04-2.png",  name: "Female 04-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 04-3.png",  name: "Female 04-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 04-4.png",  name: "Female 04-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 05-1.png",  name: "Female 05-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 05-2.png",  name: "Female 05-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 05-3.png",  name: "Female 05-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 05-4.png",  name: "Female 05-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 06-1.png",  name: "Female 06-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 06-2.png",  name: "Female 06-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 06-3.png",  name: "Female 06-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 06-4.png",  name: "Female 06-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 07-1.png",  name: "Female 07-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 07-2.png",  name: "Female 07-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 07-3.png",  name: "Female 07-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 07-4.png",  name: "Female 07-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 08-1.png",  name: "Female 08-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 08-2.png",  name: "Female 08-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 08-3.png",  name: "Female 08-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 08-4.png",  name: "Female 08-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 09-1.png",  name: "Female 09-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 09-2.png",  name: "Female 09-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 09-3.png",  name: "Female 09-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 09-4.png",  name: "Female 09-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 10-1.png",  name: "Female 10-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 10-2.png",  name: "Female 10-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 10-3.png",  name: "Female 10-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 10-4.png",  name: "Female 10-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 11-1.png",  name: "Female 11-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 11-2.png",  name: "Female 11-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 11-3.png",  name: "Female 11-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 11-4.png",  name: "Female 11-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 12-1.png",  name: "Female 12-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 12-2.png",  name: "Female 12-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 12-3.png",  name: "Female 12-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 12-4.png",  name: "Female 12-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 13-1.png",  name: "Female 13-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 13-2.png",  name: "Female 13-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 13-3.png",  name: "Female 13-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 13-4.png",  name: "Female 13-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 14-1.png",  name: "Female 14-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 14-2.png",  name: "Female 14-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 14-3.png",  name: "Female 14-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 14-4.png",  name: "Female 14-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 15-1.png",  name: "Female 15-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 15-2.png",  name: "Female 15-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 15-3.png",  name: "Female 15-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 15-4.png",  name: "Female 15-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 16-1.png",  name: "Female 16-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 16-2.png",  name: "Female 16-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 16-3.png",  name: "Female 16-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 16-4.png",  name: "Female 16-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 17-1.png",  name: "Female 17-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 17-2.png",  name: "Female 17-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 17-3.png",  name: "Female 17-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 17-4.png",  name: "Female 17-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 18-1.png",  name: "Female 18-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 18-2.png",  name: "Female 18-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 18-3.png",  name: "Female 18-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 18-4.png",  name: "Female 18-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 19-1.png",  name: "Female 19-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 19-2.png",  name: "Female 19-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 19-3.png",  name: "Female 19-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 19-4.png",  name: "Female 19-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 20-1.png",  name: "Female 20-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 20-2.png",  name: "Female 20-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 20-3.png",  name: "Female 20-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 20-4.png",  name: "Female 20-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 21-1.png",  name: "Female 21-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 21-2.png",  name: "Female 21-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 21-3.png",  name: "Female 21-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 21-4.png",  name: "Female 21-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 22-1.png",  name: "Female 22-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 22-2.png",  name: "Female 22-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 22-3.png",  name: "Female 22-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 22-4.png",  name: "Female 22-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 23-1.png",  name: "Female 23-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 24-1.png",  name: "Female 24-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Female/Female 25-1.png",  name: "Female 25-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 01.png",  name: "su1 Student fmale 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 02.png",  name: "su1 Student fmale 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 03.png",  name: "su1 Student fmale 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 04.png",  name: "su1 Student fmale 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 05.png",  name: "su1 Student fmale 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 06.png",  name: "su1 Student fmale 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 07.png",  name: "su1 Student fmale 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 08.png",  name: "su1 Student fmale 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 09.png",  name: "su1 Student fmale 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 10.png",  name: "su1 Student fmale 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 11.png",  name: "su1 Student fmale 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 12.png",  name: "su1 Student fmale 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 13.png",  name: "su1 Student fmale 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 14.png",  name: "su1 Student fmale 14", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 15.png",  name: "su1 Student fmale 15", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 16.png",  name: "su1 Student fmale 16", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 17.png",  name: "su1 Student fmale 17", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student fmale 18.png",  name: "su1 Student fmale 18", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 01.png",  name: "su1 Student male 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 02.png",  name: "su1 Student male 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 03.png",  name: "su1 Student male 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 04.png",  name: "su1 Student male 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 05.png",  name: "su1 Student male 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 06.png",  name: "su1 Student male 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 07.png",  name: "su1 Student male 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 08.png",  name: "su1 Student male 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 09.png",  name: "su1 Student male 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 10.png",  name: "su1 Student male 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 11.png",  name: "su1 Student male 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 12.png",  name: "su1 Student male 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 1/su1 Student male 13.png",  name: "su1 Student male 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 01.png",  name: "su2 Student fmale 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 02.png",  name: "su2 Student fmale 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 03.png",  name: "su2 Student fmale 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 04.png",  name: "su2 Student fmale 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 05.png",  name: "su2 Student fmale 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 06.png",  name: "su2 Student fmale 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 07.png",  name: "su2 Student fmale 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 08.png",  name: "su2 Student fmale 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 09.png",  name: "su2 Student fmale 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 10.png",  name: "su2 Student fmale 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 11.png",  name: "su2 Student fmale 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 12.png",  name: "su2 Student fmale 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 13.png",  name: "su2 Student fmale 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 14.png",  name: "su2 Student fmale 14", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 15.png",  name: "su2 Student fmale 15", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 16.png",  name: "su2 Student fmale 16", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 17.png",  name: "su2 Student fmale 17", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student fmale 18.png",  name: "su2 Student fmale 18", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 01.png",  name: "su2 Student male 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 02.png",  name: "su2 Student male 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 03.png",  name: "su2 Student male 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 04.png",  name: "su2 Student male 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 05.png",  name: "su2 Student male 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 06.png",  name: "su2 Student male 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 07.png",  name: "su2 Student male 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 08.png",  name: "su2 Student male 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 09.png",  name: "su2 Student male 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 10.png",  name: "su2 Student male 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 11.png",  name: "su2 Student male 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 12.png",  name: "su2 Student male 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 2/su2 Student male 13.png",  name: "su2 Student male 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 01.png",  name: "su3 Student fmale 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 02.png",  name: "su3 Student fmale 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 03.png",  name: "su3 Student fmale 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 04.png",  name: "su3 Student fmale 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 05.png",  name: "su3 Student fmale 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 06.png",  name: "su3 Student fmale 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 07.png",  name: "su3 Student fmale 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 08.png",  name: "su3 Student fmale 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 09.png",  name: "su3 Student fmale 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 10.png",  name: "su3 Student fmale 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 11.png",  name: "su3 Student fmale 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 12.png",  name: "su3 Student fmale 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 13.png",  name: "su3 Student fmale 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 14.png",  name: "su3 Student fmale 14", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 15.png",  name: "su3 Student fmale 15", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 16.png",  name: "su3 Student fmale 16", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 17.png",  name: "su3 Student fmale 17", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student fmale 18.png",  name: "su3 Student fmale 18", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 01.png",  name: "su3 Student male 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 02.png",  name: "su3 Student male 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 03.png",  name: "su3 Student male 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 04.png",  name: "su3 Student male 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 05.png",  name: "su3 Student male 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 06.png",  name: "su3 Student male 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 07.png",  name: "su3 Student male 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 08.png",  name: "su3 Student male 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 09.png",  name: "su3 Student male 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 10.png",  name: "su3 Student male 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 11.png",  name: "su3 Student male 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 12.png",  name: "su3 Student male 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 3/su3 Student male 13.png",  name: "su3 Student male 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 01.png",  name: "su4 Student fmale 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 02.png",  name: "su4 Student fmale 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 03.png",  name: "su4 Student fmale 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 04.png",  name: "su4 Student fmale 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 05.png",  name: "su4 Student fmale 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 06.png",  name: "su4 Student fmale 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 07.png",  name: "su4 Student fmale 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 08.png",  name: "su4 Student fmale 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 09.png",  name: "su4 Student fmale 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 10.png",  name: "su4 Student fmale 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 11.png",  name: "su4 Student fmale 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 12.png",  name: "su4 Student fmale 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 13.png",  name: "su4 Student fmale 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 14.png",  name: "su4 Student fmale 14", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 15.png",  name: "su4 Student fmale 15", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 16.png",  name: "su4 Student fmale 16", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 17.png",  name: "su4 Student fmale 17", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student fmale 18.png",  name: "su4 Student fmale 18", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 01.png",  name: "su4 Student male 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 02.png",  name: "su4 Student male 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 03.png",  name: "su4 Student male 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 04.png",  name: "su4 Student male 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 05.png",  name: "su4 Student male 05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 06.png",  name: "su4 Student male 06", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 07.png",  name: "su4 Student male 07", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 08.png",  name: "su4 Student male 08", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 09.png",  name: "su4 Student male 09", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 10.png",  name: "su4 Student male 10", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 11.png",  name: "su4 Student male 11", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 12.png",  name: "su4 Student male 12", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/school uniform 4/su4 Student male 13.png",  name: "su4 Student male 13", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Headmaster fmale.png",  name: "Headmaster fmale", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Headmaster male.png",  name: "Headmaster male", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher fmale 01.png",  name: "Teacher fmale 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher fmale 02.png",  name: "Teacher fmale 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher fmale 03.png",  name: "Teacher fmale 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher fmale 04.png",  name: "Teacher fmale 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher male 01.png",  name: "Teacher male 01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher male 02.png",  name: "Teacher male 02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher male 03.png",  name: "Teacher male 03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Japanese school characters/teachers/Teacher male 04.png",  name: "Teacher male 04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 01-1.png",  name: "Male 01-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 01-2.png",  name: "Male 01-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 01-3.png",  name: "Male 01-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 01-4.png",  name: "Male 01-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 02-1.png",  name: "Male 02-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 02-2.png",  name: "Male 02-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 02-3.png",  name: "Male 02-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 02-4.png",  name: "Male 02-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 03-1.png",  name: "Male 03-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 03-2.png",  name: "Male 03-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 03-3.png",  name: "Male 03-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 03-4.png",  name: "Male 03-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 04-1.png",  name: "Male 04-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 04-2.png",  name: "Male 04-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 04-3.png",  name: "Male 04-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 04-4.png",  name: "Male 04-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 05-1.png",  name: "Male 05-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 05-2.png",  name: "Male 05-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 05-3.png",  name: "Male 05-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 05-4.png",  name: "Male 05-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 06-1.png",  name: "Male 06-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 06-2.png",  name: "Male 06-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 06-3.png",  name: "Male 06-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 06-4.png",  name: "Male 06-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 07-1.png",  name: "Male 07-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 07-2.png",  name: "Male 07-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 07-3.png",  name: "Male 07-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 07-4.png",  name: "Male 07-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 08-1.png",  name: "Male 08-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 08-2.png",  name: "Male 08-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 08-3.png",  name: "Male 08-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 08-4.png",  name: "Male 08-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 09-1.png",  name: "Male 09-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 09-2.png",  name: "Male 09-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 09-3.png",  name: "Male 09-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 09-4.png",  name: "Male 09-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 10-1.png",  name: "Male 10-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 10-2.png",  name: "Male 10-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 10-3.png",  name: "Male 10-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 10-4.png",  name: "Male 10-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 11-1.png",  name: "Male 11-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 11-2.png",  name: "Male 11-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 11-3.png",  name: "Male 11-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 11-4.png",  name: "Male 11-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 12-1.png",  name: "Male 12-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 12-2.png",  name: "Male 12-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 12-3.png",  name: "Male 12-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 12-4.png",  name: "Male 12-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 13-1.png",  name: "Male 13-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 13-2.png",  name: "Male 13-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 13-3.png",  name: "Male 13-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 13-4.png",  name: "Male 13-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 14-1.png",  name: "Male 14-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 14-2.png",  name: "Male 14-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 14-3.png",  name: "Male 14-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 14-4.png",  name: "Male 14-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 15-1.png",  name: "Male 15-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 15-2.png",  name: "Male 15-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 15-3.png",  name: "Male 15-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 15-4.png",  name: "Male 15-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 16-1.png",  name: "Male 16-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 16-2.png",  name: "Male 16-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 16-3.png",  name: "Male 16-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 16-4.png",  name: "Male 16-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 17-1.png",  name: "Male 17-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 17-2.png",  name: "Male 17-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 17-3.png",  name: "Male 17-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 17-4.png",  name: "Male 17-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Male/Male 18-1.png",  name: "Male 18-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Other/pien.png",  name: "pien", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Other/pien2.png",  name: "pien2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Other/pipo-charachip_otaku01.png",  name: "pipo-charachip_otaku01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Other/pipo-charachip_soldier01.png",  name: "pipo-charachip_soldier01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 01-1.png",  name: "Soldier 01-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 01-2.png",  name: "Soldier 01-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 01-3.png",  name: "Soldier 01-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 01-4.png",  name: "Soldier 01-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 02-1.png",  name: "Soldier 02-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 02-2.png",  name: "Soldier 02-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 02-3.png",  name: "Soldier 02-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 02-4.png",  name: "Soldier 02-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 03-1.png",  name: "Soldier 03-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 03-2.png",  name: "Soldier 03-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 03-3.png",  name: "Soldier 03-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 03-4.png",  name: "Soldier 03-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 04-1.png",  name: "Soldier 04-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 04-2.png",  name: "Soldier 04-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 04-3.png",  name: "Soldier 04-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 04-4.png",  name: "Soldier 04-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 05-1.png",  name: "Soldier 05-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 05-2.png",  name: "Soldier 05-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 05-3.png",  name: "Soldier 05-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 05-4.png",  name: "Soldier 05-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 06-1.png",  name: "Soldier 06-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 06-2.png",  name: "Soldier 06-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 06-3.png",  name: "Soldier 06-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 06-4.png",  name: "Soldier 06-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 07-1.png",  name: "Soldier 07-1", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 07-2.png",  name: "Soldier 07-2", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 07-3.png",  name: "Soldier 07-3", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Soldier/Soldier 07-4.png",  name: "Soldier 07-4", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Xmas/pipo-xmaschara01.png",  name: "pipo-xmaschara01", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Xmas/pipo-xmaschara02.png",  name: "pipo-xmaschara02", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Xmas/pipo-xmaschara03.png",  name: "pipo-xmaschara03", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Xmas/pipo-xmaschara04.png",  name: "pipo-xmaschara04", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Xmas/pipo-xmaschara05.png",  name: "pipo-xmaschara05", type: "image" },
{ src: "./data/PIPOYA FREE RPG Character Sprites 32x32/Xmas/pipo-xmaschara06.png",  name: "pipo-xmaschara06", type: "image" },
{ src: "./data/tilesets/minideko.png",  name: "minideko", type: "image" },
{ src: "./data/tilesets/cija_32x32_basic_CC0.png",  name: "cija_32x32_basic_CC0", type: "image" },
{ src: "./data/tilesets/rc3-2021-mullana-utility.png",  name: "rc3-2021-mullana-utility", type: "image" },
{ src: "./data/tilesets/rc3-mullana-floor-wall.png",  name: "rc3-mullana-floor-wall", type: "image" },
]; export default DataManifest;
