export const DataManifest = [
{ src: "./data/fnt/PressStart2P.fnt",  name: "PressStart2P", type: "binary" },
{ src: "./data/fnt/PressStart2P.png",  name: "PressStart2P", type: "image" },
{ src: "./data/tilesets/cija_32x32_basic_CC0.png",  name: "cija_32x32_basic_CC0", type: "image" },
{ src: "./data/tilesets/minideko.png",  name: "minideko", type: "image" },
{ src: "./data/tilesets/rc3-2021-mullana-utility.png",  name: "rc3-2021-mullana-utility", type: "image" },
{ src: "./data/tilesets/rc3-mullana-floor-wall.png",  name: "rc3-mullana-floor-wall", type: "image" },
{ src: "./data/map/artworld.tmx",  name: "artworld", type: "tmx" },
{ src: "./data/map/lobby.tmx",  name: "lobby", type: "tmx" },
];
export const Characters = [
{ src: "./data/characters_32px/Animal/Cat 01-1r.png",  name: "Cat 01-1r", type: "image" },
{ src: "./data/characters_32px/Animal/Cat 01-2.png",  name: "Cat 01-2", type: "image" },
{ src: "./data/characters_32px/Animal/Cat 01-3.png",  name: "Cat 01-3", type: "image" },
{ src: "./data/characters_32px/Animal/Cat-01-2r.png",  name: "Cat-01-2r", type: "image" },
{ src: "./data/characters_32px/Animal/Cat-01-3r.png",  name: "Cat-01-3r", type: "image" },
{ src: "./data/characters_32px/Animal/Dog 01-1.png",  name: "Dog 01-1", type: "image" },
{ src: "./data/characters_32px/Animal/Dog 01-1r.png",  name: "Dog 01-1r", type: "image" },
{ src: "./data/characters_32px/Animal/Dog 01-2.png",  name: "Dog 01-2", type: "image" },
{ src: "./data/characters_32px/Animal/Dog 01-3.png",  name: "Dog 01-3", type: "image" },
{ src: "./data/characters_32px/Animal/Dog-01-2r.png",  name: "Dog-01-2r", type: "image" },
{ src: "./data/characters_32px/Animal/Dog-01-3r.png",  name: "Dog-01-3r", type: "image" },
{ src: "./data/characters_32px/Female/Female 01-1.png",  name: "Female 01-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 01-2.png",  name: "Female 01-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 01-3.png",  name: "Female 01-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 01-4.png",  name: "Female 01-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 02-1.png",  name: "Female 02-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 02-2.png",  name: "Female 02-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 02-3.png",  name: "Female 02-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 02-4.png",  name: "Female 02-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 03-1.png",  name: "Female 03-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 03-2.png",  name: "Female 03-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 03-3.png",  name: "Female 03-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 03-4.png",  name: "Female 03-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 04-1.png",  name: "Female 04-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 04-2.png",  name: "Female 04-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 04-3.png",  name: "Female 04-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 04-4.png",  name: "Female 04-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 05-1.png",  name: "Female 05-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 05-2.png",  name: "Female 05-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 05-3.png",  name: "Female 05-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 05-4.png",  name: "Female 05-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 06-1.png",  name: "Female 06-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 06-2.png",  name: "Female 06-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 06-3.png",  name: "Female 06-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 06-4.png",  name: "Female 06-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 08-1.png",  name: "Female 08-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 08-2.png",  name: "Female 08-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 08-3.png",  name: "Female 08-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 08-4.png",  name: "Female 08-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 09-1.png",  name: "Female 09-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 09-2.png",  name: "Female 09-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 09-3.png",  name: "Female 09-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 09-4.png",  name: "Female 09-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 10-1.png",  name: "Female 10-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 10-2.png",  name: "Female 10-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 10-3.png",  name: "Female 10-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 10-4.png",  name: "Female 10-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 11-1.png",  name: "Female 11-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 11-2.png",  name: "Female 11-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 11-3.png",  name: "Female 11-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 11-4.png",  name: "Female 11-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 12-1.png",  name: "Female 12-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 12-2.png",  name: "Female 12-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 12-3.png",  name: "Female 12-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 12-4.png",  name: "Female 12-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 13-1.png",  name: "Female 13-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 13-2.png",  name: "Female 13-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 13-3.png",  name: "Female 13-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 13-4.png",  name: "Female 13-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 14-1.png",  name: "Female 14-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 14-2.png",  name: "Female 14-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 14-3.png",  name: "Female 14-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 14-4.png",  name: "Female 14-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 15-1.png",  name: "Female 15-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 15-2.png",  name: "Female 15-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 15-3.png",  name: "Female 15-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 15-4.png",  name: "Female 15-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 16-1.png",  name: "Female 16-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 16-2.png",  name: "Female 16-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 16-3.png",  name: "Female 16-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 16-4.png",  name: "Female 16-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 18-1.png",  name: "Female 18-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 18-2.png",  name: "Female 18-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 18-3.png",  name: "Female 18-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 18-4.png",  name: "Female 18-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 20-1.png",  name: "Female 20-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 20-2.png",  name: "Female 20-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 20-3.png",  name: "Female 20-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 20-4.png",  name: "Female 20-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 21-1.png",  name: "Female 21-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 21-2.png",  name: "Female 21-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 21-3.png",  name: "Female 21-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 21-4.png",  name: "Female 21-4", type: "image" },
{ src: "./data/characters_32px/Female/Female 22-1.png",  name: "Female 22-1", type: "image" },
{ src: "./data/characters_32px/Female/Female 22-2.png",  name: "Female 22-2", type: "image" },
{ src: "./data/characters_32px/Female/Female 22-3.png",  name: "Female 22-3", type: "image" },
{ src: "./data/characters_32px/Female/Female 22-4.png",  name: "Female 22-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 01-1.png",  name: "Male 01-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 01-2.png",  name: "Male 01-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 01-3.png",  name: "Male 01-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 01-4.png",  name: "Male 01-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 02-1.png",  name: "Male 02-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 02-2.png",  name: "Male 02-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 02-3.png",  name: "Male 02-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 02-4.png",  name: "Male 02-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 04-1.png",  name: "Male 04-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 04-2.png",  name: "Male 04-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 04-3.png",  name: "Male 04-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 04-4.png",  name: "Male 04-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 05-1.png",  name: "Male 05-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 05-2.png",  name: "Male 05-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 05-3.png",  name: "Male 05-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 05-4.png",  name: "Male 05-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 06-1.png",  name: "Male 06-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 06-2.png",  name: "Male 06-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 06-3.png",  name: "Male 06-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 06-4.png",  name: "Male 06-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 09-1.png",  name: "Male 09-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 09-2.png",  name: "Male 09-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 09-3.png",  name: "Male 09-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 09-4.png",  name: "Male 09-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 10-1.png",  name: "Male 10-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 10-2.png",  name: "Male 10-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 10-3.png",  name: "Male 10-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 10-4.png",  name: "Male 10-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 11-1.png",  name: "Male 11-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 11-2.png",  name: "Male 11-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 11-3.png",  name: "Male 11-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 11-4.png",  name: "Male 11-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 13-1.png",  name: "Male 13-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 13-2.png",  name: "Male 13-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 13-3.png",  name: "Male 13-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 13-4.png",  name: "Male 13-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 14-1.png",  name: "Male 14-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 14-2.png",  name: "Male 14-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 14-3.png",  name: "Male 14-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 14-4.png",  name: "Male 14-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 15-1.png",  name: "Male 15-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 15-2.png",  name: "Male 15-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 15-3.png",  name: "Male 15-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 15-4.png",  name: "Male 15-4", type: "image" },
{ src: "./data/characters_32px/Male/Male 16-1.png",  name: "Male 16-1", type: "image" },
{ src: "./data/characters_32px/Male/Male 16-2.png",  name: "Male 16-2", type: "image" },
{ src: "./data/characters_32px/Male/Male 16-3.png",  name: "Male 16-3", type: "image" },
{ src: "./data/characters_32px/Male/Male 16-4.png",  name: "Male 16-4", type: "image" },
];
export const Artworld = [
{ src: "./data/artworks/artworld/foorbie/foorbie_briefumschlag.png",  name: "foorbie_briefumschlag", type: "image" },
{ src: "./data/artworks/artworld/foorbie/foorbie_orchidee.png",  name: "foorbie_orchidee", type: "image" },
{ src: "./data/artworks/artworld/foorbie/foorbie_riss.png",  name: "foorbie_riss", type: "image" },
{ src: "./data/artworks/artworld/kawaiipunk/kawaiipunk_AntiFa_Area_No_Copsz.png",  name: "kawaiipunk_AntiFa_Area_No_Copsz", type: "image" },
{ src: "./data/artworks/artworld/kawaiipunk/kawaiipunk_brutualistpunk.png",  name: "kawaiipunk_brutualistpunk", type: "image" },
{ src: "./data/artworks/artworld/kawaiipunk/kawaiipunk_london.png",  name: "kawaiipunk_london", type: "image" },
{ src: "./data/artworks/artworld/kawaiipunk/kawaiipunk_self_portrait.png",  name: "kawaiipunk_self_portrait", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_107.png",  name: "km_107", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_108.png",  name: "km_108", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_115.png",  name: "km_115", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_122.png",  name: "km_122", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_123.png",  name: "km_123", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_124.png",  name: "km_124", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_125.png",  name: "km_125", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_125_part.png",  name: "km_125_part", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_127.png",  name: "km_127", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_132.png",  name: "km_132", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_133.png",  name: "km_133", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_134.png",  name: "km_134", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_135.png",  name: "km_135", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_136.png",  name: "km_136", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_137.png",  name: "km_137", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_138.png",  name: "km_138", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_140.png",  name: "km_140", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_141.png",  name: "km_141", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_142.png",  name: "km_142", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_36.png",  name: "km_36", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_41.png",  name: "km_41", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_61.png",  name: "km_61", type: "image" },
{ src: "./data/artworks/artworld/kittenmews/km_79.png",  name: "km_79", type: "image" },
{ src: "./data/artworks/artworld/lyrilith/lyrilith_83cc92e895a4fcfb.png",  name: "lyrilith_83cc92e895a4fcfb", type: "image" },
{ src: "./data/artworks/artworld/lyrilith/lyrilith_c90963e341da1cec.png",  name: "lyrilith_c90963e341da1cec", type: "image" },
{ src: "./data/artworks/artworld/p5t/p5t_star.png",  name: "p5t_star", type: "image" },
];
